#==============================================================================
#	Wonder Swan Total Sound Driver
#		Software Development kit
#			Make file
#				A.Waranabe (S.W.)
#==============================================================================

ASM = masm
AFLAG = /IC:\WWitch\WTD\SDK\include /ML /MX

CC = lcc86
CFLAG = -m

LINKER = link
LFLAG = /tiny
LIBS = C:\WWitch\LIB\libww.lib

LIB = lib
