del WTDMAKE.wup
del readme.wup
del 取説.wup
del devloper.wup
del WTDMAKE.com
del readme.COM
del 取説.COM
del devloper.COM
DEL wtdil.lzh


c:\lsic86\WSP -W -A .\OLD_WTD\wtdil.hed wtdil.hed WTDMAKE.WUP

c:\lsic86\WSP -W -A .\OLD_WTD\wtd.fx wtd.fx WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtd_h.fx wtd_h.fx WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wmsvwtd.fx wmsvwtd.fx WTDMAKE.WUP

c:\lsic86\WSP -W -A .\OLD_WTD\wtc.com wtc.com WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtc_h.com wtc_h.com WTDMAKE.WUP

c:\lsic86\WSP -W -A .\OLD_WTD\service.inc service.inc WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\timer.inc timer.inc WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\comm.inc comm.inc WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\sound.inc sound.inc WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtd.h wtd.h WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtd_def.inc wtd_def.inc WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtd_ver.inc wtd_ver.inc WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtc_def.inc wtc_def.inc WTDMAKE.WUP

c:\lsic86\WSP -W -A .\OLD_WTD\wtd.asm wtd.asm WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtd_h.asm wtd_h.asm WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtd_ilf.asm wtd_ilf.asm WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtd_int.asm wtd_int.asm WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtd_tim.asm wtd_tim.asm WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtd_com.asm wtd_com.asm WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtd_snd.asm wtd_snd.asm WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtd.asm wtd.asm WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtd_h.asm wtd_h.asm WTDMAKE.WUP

c:\lsic86\WSP -W -A .\OLD_WTD\wtc.asm wtc.asm WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtc_h.asm wtc_h.asm WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtc_main.asm wtc_main.asm WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtc_sub.asm wtc_sub.asm WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtc_hed.asm wtc_hed.asm WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtc_voi.asm wtc_voi.asm WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtc_com.asm wtc_com.asm WTDMAKE.WUP

rem ●c:\lsic86\WSP -W -A .\OLD_WTD\セレクタソースファイル

c:\lsic86\WSP -W -A .\OLD_WTD\wtd_make.bat wtd_make.bat WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtd_wsp.bat wtd_wsp.bat WTDMAKE.WUP
rem ●c:\lsic86\WSP -W -A .\OLD_WTD\セレクタメイクファイル

c:\lsic86\WSP -W -A .\OLD_WTD\wtd.cf wtd.cf WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wtd_h.cf wtd_h.cf WTDMAKE.WUP
rem ●c:\lsic86\WSP -W -A .\OLD_WTD\セレクタcfファイル

c:\lsic86\WSP -W -A .\OLD_WTD\wtd_his.txt wtd_his.txt WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\wmsv_his.txt wmsv_his.txt WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\fspnet.txt fspnet.txt WTDMAKE.WUP

c:\lsic86\WSP -W -A .\OLD_WTD\readme.doc readme.doc WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\取説.doc 取説.doc WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\devloper.doc devloper.doc WTDMAKE.WUP

c:\lsic86\WSP -W -A .\OLD_WTD\取説_表.xls 取説_表.xls WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\dev_表.xls dev_表.xls WTDMAKE.WUP
c:\lsic86\WSP -W -A .\OLD_WTD\buy.xls buy.xls WTDMAKE.WUP

c:\lsic86\WSP -S WTDMAKE.WUP WTDMAKE.COM

c:\lsic86\WSP -W -A .\OLD_WTD\readme.pdf readme.pdf readme.WUP
c:\lsic86\WSP -S readme.WUP readme.COM
c:\lsic86\WSP -W -A .\OLD_WTD\取説.pdf 取説.pdf 取説.WUP
c:\lsic86\WSP -S 取説.WUP 取説.COM
c:\lsic86\WSP -W -A .\OLD_WTD\devloper.PDF devloper.PDF devloper.WUP
c:\lsic86\WSP -S devloper.WUP devloper.COM


c:\lsic86\lha a wtdil.lzh  wtdil.hed
c:\lsic86\lha a wtdil.lzh  WTDMAKE.com readme.COM 取説.COM devloper.COM

