#==============================================================================
#	Wonder Swan Total Sound Driver
#		MML Compiler
#			Make file
#				A.Waranabe (S.W.)
#==============================================================================
include ..\..\..\SDK\include\wtdsdk.mak

PROJ = DAT2ASM

INC_FILES =  ..\..\..\SDK\include\wtd_def.inc ..\..\..\SDK\include\wtd_ver.inc

FILES = DAT2ASM.ASM D2A_CNV.ASM

all: $(PROJ).com
	@del *.bak
	@del *.obj
	@del *.exe
	@del *.bin

$(PROJ).com : $(FILES) $(INC_FILES)
	@$(ASM) $(AFLAG) /la $(PROJ);>d2aerr.txt
	@$(LINKER) $(LFLAG) $(PROJ),,,$(LIBFILES);
