#==============================================================================
#	Wonder Swan Total Sound Driver
#		MML Compiler
#			Make file
#				A.Waranabe (S.W.)
#==============================================================================
include ..\..\..\SDK\include\wtdsdk.mak

PROJ = DAT2ASM

INC_FILES =  ..\..\..\SDK\include\wtd.h ..\..\..\SDK\include\bank.inc ..\..\..\SDK\include\comm.inc ..\..\..\SDK\include\process.inc ..\..\..\SDK\include\service.inc ..\..\..\SDK\include\sound.inc ..\..\..\SDK\include\timer.inc ..\..\..\SDK\include\wtd_def.inc ..\..\..\SDK\include\wtd_ver.inc ..\..\..\SDK\include\wtc_def.inc ..\..\..\SDK\include\WSMAKE.INC

FILES = DAT2ASM.ASM D2A_SUB.ASM D2A_CNV.ASM

all: $(PROJ).com
	@del *.bak
	@del *.obj
	@del *.exe
	@del *.bin

$(PROJ).com : $(FILES) $(INC_FILES)
	@$(ASM) $(AFLAG) $(PROJ);>d2aerr.txt
	@$(LINKER) $(LFLAG) $(PROJ),,,$(LIBS);
